name: Build and Publish .NET Core Application

on:
  push:
    branches:
      - main # or your default branch
  pull_request:
    branches:
      - main # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x" # Specify your .NET version

      - name: Restore dependencies
        run: dotnet restore WebApi/Poc.Api

      - name: Build
        run: dotnet build WebApi/Poc.Api --no-restore -c Release

      # - name: Test
      #   run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish  WebApi/Poc.Api --no-build -c Release -o ${{github.workspace}}/publish

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: net-core-app
          path: ${{github.workspace}}/publish
          retention-days: 7
